variable "ami_name" {}
variable "launch-template-name1" {}
variable "launch-template-name2" {}
variable "web-sg-name" {}
variable "was-sg-name" {}
variable "web-tg-name" {}
variable "was-tg-name" {}
variable "iam-role" {}
variable "public-subnet-name1" {}
variable "public-subnet-name2" {}
variable "private1-subnet-name1" {}
variable "private1-subnet-name2" {}
variable "instance-profile-name" {}
variable "asg-name1" {}
variable "asg-name2" {}